### ISSUE TITLE
Help files

### ISSUE THREAD

**Issue by nightairjj** [alan-agius4/speedy-json-extends#28]
packages/ngtools/webpack/src/paths-plugin.ts

import { json } from "@speedy/json-extends";

const named = {
  "@speedy/commit-msg-hook:latest": "./node_modules/config/config.json"
};

json.read("local-config.json", named)
  .then(content => {
    // json content
  });
{
  "extends": [
    "@speedy/commit-msg-hook:latest",
    "./local/config.json"
  ],
  "rules": {
    "no-dash": true
  }
}
import { json } from "@speedy/json-extends";

const named = {
  "@speedy/commit-msg-hook:latest": "./node_modules/config/config.json"
};

const content = json.readSync("local-config.json", named);
828224

**Comment by alan-agius4** [comment]
I am sorry but I am not understanding the issue.
